replicaCount: 6

image:
  repository: kanupriya18/calculator
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort  # Change to ClusterIP if internal only
  port: 5000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

securityContext:
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
  allowPrivilegeEscalation: false

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
  prometheus.io/port: "5000"

nodeSelector: {}

tolerations: []

affinity: {}

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    labels:
      release: prometheus

alerting:
  enabled: true
  alertRules:
    podFailureThreshold: 3
    duration: 2m
  slack:
    enabled: true
    webhookUrl: "<your-slack-webhook-url>"
    channel: "#project01-alerts"
    sendResolved: true

openshift:
  route:
    enabled: true
    host: "project01.apps.openshift.example.com"
    tls:
      enabled: true
      termination: edge
      certificate: "<your-ssl-cert>"
      key: "<your-ssl-key>"
